.TH "bmcore::sPlatformInfo" 3 "Tue Feb 26 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmcore::sPlatformInfo \- 
.PP
Contains members representing the plaform critical information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cHardwarePlatform\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "tReal32 \fBCPUSpeed\fP"
.br
.ti -1c
.RI "tReal32 \fBdiskAccess\fP"
.br
.RI "\fIThe CPU speed\&. \fP"
.ti -1c
.RI "tReal32 \fBdiskRead\fP"
.br
.RI "\fIavg disk access speed \fP"
.ti -1c
.RI "tuInt32 \fBnumCPUs\fP"
.br
.RI "\fIavg disk read speed \fP"
.ti -1c
.RI "tuInt32 \fBnumMemBanks\fP"
.br
.RI "\fINumber of processor cores\&. \fP"
.ti -1c
.RI "tMemSize \fBmemSize\fP"
.br
.RI "\fINumber of memory slots\&. \fP"
.ti -1c
.RI "tuChar8 * \fBname\fP"
.br
.RI "\fITotal physical memory\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains members representing the plaform critical information\&. 
.PP
Definition at line 19 of file cHardwarePlatform\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
