.TH "bmcore::cHardwarePlatform_Unix" 3 "Tue Feb 26 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmcore::cHardwarePlatform_Unix \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbmcore::cHardwarePlatform\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file cHardwarePlatform_Unix\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
