.TH "bmengine/bmdebug_win.h" 3 "Tue Feb 26 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine/bmdebug_win.h \- 
.PP
Windows specific defines and includes for debugging\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'datatypes\&.h'\fP
.br
\fC#include 'bmutil_defines\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "BM_INLINE void \fBBMOutputTraceMsg\fP (const tChar8 *iMsg)"
.br
.ti -1c
.RI "BM_INLINE void \fBBMOutputTrace\fP (tuInt16 idx, const tChar8 *iFile, tMemSize iLine, const tChar8 *iMsg,\&.\&.\&.)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Windows specific defines and includes for debugging\&. 


.PP
Definition in file \fBbmdebug_win\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
