.TH "bmengine/bmplatform.h" 3 "Tue Feb 26 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine/bmplatform.h \- 
.PP
Provides platform/compiler specific defines and includes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNIX\fP   1"
.br
.ti -1c
.RI "#define \fBWINDOWS\fP   0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides platform/compiler specific defines and includes\&. 


.PP
Definition in file \fBbmplatform\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
