.TH "bmengine/cDebugger.h" 3 "Tue Feb 26 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine/cDebugger.h \- 
.PP
Main include header for debugger functionality\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <cstdarg>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'bmplatform\&.h'\fP
.br
\fC#include 'datatypes\&.h'\fP
.br
\fC#include 'bmutil_defines\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbmutil::cDebugger\fP"
.br
.RI "\fIDebug module driver\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBM_ERR_FATAL\fP   5"
.br
.ti -1c
.RI "#define \fBBM_ERR_ERROR\fP   4"
.br
.ti -1c
.RI "#define \fBBM_ERR_WARNING\fP   3"
.br
.ti -1c
.RI "#define \fBBM_ERR_MESSAGE\fP   2"
.br
.ti -1c
.RI "#define \fBBM_ERR_INFO\fP   1"
.br
.ti -1c
.RI "#define \fBBM_ERR_REPORT_NONE\fP   6"
.br
.ti -1c
.RI "#define \fBBM_ERR_REPORT_ALL\fP   0"
.br
.ti -1c
.RI "#define \fBSID_FATAL\fP(msg)   BM_ERR_FATAL,__FILE__,__LINE__,msg"
.br
.ti -1c
.RI "#define \fBSID_ERROR\fP(msg)   BM_ERR_ERROR,__FILE__,__LINE__,msg"
.br
.ti -1c
.RI "#define \fBSID_WARNING\fP(msg)   BM_ERR_WARNING,__FILE__,__LINE__,msg"
.br
.ti -1c
.RI "#define \fBSID_MESSAGE\fP(msg)   BM_ERR_MESSAGE,__FILE__,__LINE__,msg"
.br
.ti -1c
.RI "#define \fBSID_INFO\fP(msg)   BM_ERR_INFO,__FILE__,__LINE__,msg"
.br
.ti -1c
.RI "#define \fBBMTrace\fP   sizeof"
.br
.ti -1c
.RI "#define \fBBMAssert\fP(b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main include header for debugger functionality\&. 


.PP
Definition in file \fBcDebugger\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
