.TH "bmengine/cDebugger_Win.h" 3 "Tue Feb 26 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine/cDebugger_Win.h \- 
.PP
Contains windows specific debugging classes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'cDebugger\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbmutil::cDebugger_Win\fP"
.br
.RI "\fIWindows implementation of the debug module driver\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains windows specific debugging classes\&. 


.PP
Definition in file \fBcDebugger_Win\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
