.TH "cHardwarePlatform" 3 "Fri Jan 25 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cHardwarePlatform \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcHardwarePlatform_Win\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual tReal32 \fBgetCPUSpeed\fP (void)"
.br
.RI "\fIGets the CPU speed\&. \fP"
.ti -1c
.RI "virtual tuChar8 * \fBgetDevURL\fP (void)"
.br
.ti -1c
.RI "virtual tReal32 \fBgetDiskAccessSpeed\fP (void)"
.br
.ti -1c
.RI "virtual tReal32 \fBgetDiskReadSpeed\fP (void)"
.br
.ti -1c
.RI "virtual tuChar8 * \fBgetDocsURL\fP (void)"
.br
.ti -1c
.RI "virtual tMemSize \fBgetMemorySize\fP (void)"
.br
.ti -1c
.RI "virtual tuInt32 \fBgetNumCPUs\fP (void)"
.br
.ti -1c
.RI "virtual tuInt32 \fBgetNumMemBanks\fP (void)"
.br
.ti -1c
.RI "virtual tuChar8 * \fBgetPlatform\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcHardwarePlatform\fP * \fBGet\fP (void)"
.br
.RI "\fIGets this instance\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file cHardwarePlatform\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBcHardwarePlatform\fP * cHardwarePlatform::Get (void)\fC [static]\fP"

.PP
Gets this instance\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 12 of file cHardwarePlatform\&.cpp\&.
.PP
.nf
{
#if WINDOWS
    return cHardwarePlatform_Win::Get();
#elif UNIX
    return cHardwarePlatform_Unix::Get();
#else
    if (NULL == sm_pinstance){sm_pinstance = new cHardwarePlatform();}
    return sm_pinstance;
#endif
}
.fi
.SS "tReal32 cHardwarePlatform::getCPUSpeed (void)\fC [virtual]\fP"

.PP
Gets the CPU speed\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Reimplemented in \fBcHardwarePlatform_Win\fP\&.
.PP
Definition at line 40 of file cHardwarePlatform\&.cpp\&.
.PP
.nf
{
    return 0\&.0;
}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
