.TH "bmengine/cHardwarePlatform.h" 3 "Fri Jan 25 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine/cHardwarePlatform.h \- 
.PP
Provides declarations for the abstracted/null driver hardware platform class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'datatypes\&.h'\fP
.br
\fC#include 'platform\&.h'\fP
.br
\fC#include 'cHardwarePlatform_Win\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsPlatformInfo\fP"
.br
.ti -1c
.RI "class \fBcHardwarePlatform\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides declarations for the abstracted/null driver hardware platform class\&. 


.PP
Definition in file \fBcHardwarePlatform\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
