.TH "bmengine/cHardwarePlatform_Win.h" 3 "Tue Feb 26 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine/cHardwarePlatform_Win.h \- 
.PP
Provides declarations for windows-specific hardware platform\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <comdef\&.h>\fP
.br
\fC#include <Wbemidl\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <Windows\&.h>\fP
.br
\fC#include 'datatypes\&.h'\fP
.br
\fC#include 'cHardwarePlatform\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbmcore::cHardwarePlatform_Win\fP"
.br
.RI "\fIWindows specific implementation for the cHardwarPlatform class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides declarations for windows-specific hardware platform\&. 


.PP
Definition in file \fBcHardwarePlatform_Win\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
