.TH "bmengine/core.h" 3 "Tue Feb 12 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine/core.h \- 
.PP
Contains includes for the core namespace of the BMEngine\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'bmplatform\&.h'\fP
.br
\fC#include 'bmmemory\&.h'\fP
.br
\fC#include 'cHardwarePlatform\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Contains includes for the core namespace of the BMEngine\&. 


.PP
Definition in file \fBcore\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
