.TH "bmengine Directory Reference" 3 "Thu Jan 24 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcHardwarePlatform\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcHardwarePlatform\&.h\fP"
.br
.RI "\fIProvides declarations for the abstracted/null driver hardware platform class\&. \fP"
.ti -1c
.RI "file \fBcHardwarePlatform_Win\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcHardwarePlatform_Win\&.h\fP"
.br
.RI "\fIProvides declarations for windows-specific hardware platform\&. \fP"
.ti -1c
.RI "file \fBcMemory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcMemory\&.h\fP"
.br
.ti -1c
.RI "file \fBcore\&.h\fP"
.br
.RI "\fIContains includes for the core namespace of the BMEngine\&. \fP"
.ti -1c
.RI "file \fBdatatypes\&.h\fP"
.br
.RI "\fIProvides the directed include of abstracted dataypes\&. \fP"
.ti -1c
.RI "file \fBdatatypes_Unix\&.h\fP"
.br
.ti -1c
.RI "file \fBdatatypes_Win\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBplatform\&.h\fP"
.br
.RI "\fIProvides platform/compiler specific defines and includes\&. \fP"
.in -1c
