.TH "bmengine Directory Reference" 3 "Tue Feb 12 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbmdebug\&.h\fP"
.br
.ti -1c
.RI "file \fBbmdebug_win\&.h\fP"
.br
.RI "\fIWindows specific defines and includes for debugging\&. \fP"
.ti -1c
.RI "file \fBbmmemory\&.h\fP"
.br
.RI "\fIGeneral include file to be used by other code to include the memory subsystem\&. \fP"
.ti -1c
.RI "file \fBbmplatform\&.h\fP"
.br
.RI "\fIProvides platform/compiler specific defines and includes\&. \fP"
.ti -1c
.RI "file \fBbmutil\&.h\fP"
.br
.RI "\fIGeneral included header for all utility headers\&. \fP"
.ti -1c
.RI "file \fBbmutil_defines\&.h\fP"
.br
.RI "\fIDeclares all util namespace related defines and Macros\&. \fP"
.ti -1c
.RI "file \fBcDebugger\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcDebugger\&.h\fP"
.br
.RI "\fIMain include header for debugger functionality\&. \fP"
.ti -1c
.RI "file \fBcDebugger_Win\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcDebugger_Win\&.h\fP"
.br
.RI "\fIContains windows specific debugging classes\&. \fP"
.ti -1c
.RI "file \fBcHardwarePlatform\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcHardwarePlatform\&.h\fP"
.br
.RI "\fIProvides declarations for the abstracted/null driver hardware platform class\&. \fP"
.ti -1c
.RI "file \fBcHardwarePlatform_Win\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcHardwarePlatform_Win\&.h\fP"
.br
.RI "\fIProvides declarations for windows-specific hardware platform\&. \fP"
.ti -1c
.RI "file \fBcMemory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcMemory\&.h\fP"
.br
.ti -1c
.RI "file \fBcore\&.h\fP"
.br
.RI "\fIContains includes for the core namespace of the BMEngine\&. \fP"
.ti -1c
.RI "file \fBdatatypes\&.h\fP"
.br
.RI "\fIProvides the directed include of abstracted dataypes\&. \fP"
.ti -1c
.RI "file \fBdatatypes_Unix\&.h\fP"
.br
.ti -1c
.RI "file \fBdatatypes_Win\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsanity\&.h\fP"
.br
.in -1c
