.TH "bmengine/datatypes.h" 3 "Tue Feb 26 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine/datatypes.h \- 
.PP
Provides the directed include of abstracted dataypes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include 'bmplatform\&.h'\fP
.br
\fC#include 'datatypes_Unix\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBM_ENUM_PADDING\fP   0x7fffffff"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides the directed include of abstracted dataypes\&. 


.PP
Definition in file \fBdatatypes\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
