.TH "bmengine/platform.h" 3 "Thu Jan 24 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmengine/platform.h \- 
.PP
Provides platform/compiler specific defines and includes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNIX\fP   0"
.br
.ti -1c
.RI "#define \fBWINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBBM_INLINE\fP   inline"
.br
.ti -1c
.RI "#define \fBBMAssert\fP(b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides platform/compiler specific defines and includes\&. 


.PP
Definition in file \fBplatform\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BM_INLINE   inline"
End platform includes 
.PP
Definition at line 30 of file platform\&.h\&.
.SS "#define BMAssert(b)"
End Inlining defines 
.PP
Definition at line 55 of file platform\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
