.TH "sBlockHeader" 3 "Thu Jan 24 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sBlockHeader \- 
.PP
Represents the header for a memory block in the BME memory manager\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cMemory\&.h>\fP
.SH "Detailed Description"
.PP 
Represents the header for a memory block in the BME memory manager\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
