.TH "sPlatformInfo" 3 "Fri Jan 25 2013" "Version 0.1" "Bad Monkey Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sPlatformInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "tReal32 \fBCPUSpeed\fP"
.br
.ti -1c
.RI "tReal32 \fBdiskAccess\fP"
.br
.ti -1c
.RI "tReal32 \fBdiskRead\fP"
.br
.ti -1c
.RI "tuInt32 \fBnumCPUs\fP"
.br
.ti -1c
.RI "tuInt32 \fBnumMemBanks\fP"
.br
.ti -1c
.RI "tMemSize \fBmemSize\fP"
.br
.ti -1c
.RI "tuChar8 * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file cHardwarePlatform\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bad Monkey Engine from the source code\&.
